.MODEL SMALL
.STACK 100H
.DATA
        PROMP1 DB 10,13, "ENTER A NUMBER IN HEXA-DECIMAL : $ "
        PROMP2 DB 10,13, "ITS BINARY EQUIVALENT IS : $ "
        PROMP3 DB 10,13, "IT IS PALINDROM IN BINARY.$"
        PROMP4 DB 10,13, "IT IS NOT A PALINDROM IN BINARY.$"
.CODE
MAIN PROC
        MOV AX,@DATA
        MOV DS,AX
        
		
        MOV AH,4CH
        INT 21H
		
MAIN ENDP
END MAIN
